### ISSUE TITLE
Pantheon logo often appears oversized in admin bar

### ISSUE THREAD

**Issue by westonruter** [pantheon-systems/pantheon-hud#64]
Sometimes the CSS from #26 doesn't appear, resulting in the logo often appearing oversized:

![image](https://user-images.githubusercontent.com/134745/84600155-405f4180-ae2c-11ea-9e7f-7eb761af2959.png)

Specifically, this CSS rule is missing from the page:

```css
#wpadminbar li#wp-admin-bar-pantheon-hud > .ab-item img {
    height: 32px;
    width: 32px;
    vertical-align: middle;
    margin-top: -4px;
}
```

Nevertheless, when I reload the page then the CSS rule re-appears and logo is properly sized. The issue reoccurs the first time visiting the admin each time I flush the cache for the environment.

This leads me to think that maybe this is a regression introduced by lazy-loading the submenu contents upon hover (#55).
